# 💻 Microsoft (MSFT) Stock Price Analysis – Last 5 Years

This notebook explores historical stock data for Microsoft Corp. (Ticker: MSFT).  
We will perform basic data loading, exploration, and visualization techniques.

In [1]:
# importing the libraries 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Optional: configure plots
sns.set(style="darkgrid")
plt.rcParams["figure.figsize"] = (12, 6)

In [2]:
# Replace 'msft_stock_data.csv' with your actual file name/path
df = pd.read_csv('/kaggle/input/microsoft-stock-price-data-last-5-years/microsoft_5yr_one.csv', parse_dates=['Date'])
df.head()

,Date,Close,High,Low,Open,Volume
0,NaT,MSFT,MSFT,MSFT,MSFT,MSFT
1,2020-06-04,175.25303649902344,178.05064502079156,174.65902803636578,176.57519945833528,28761800
2,2020-06-05,179.35362243652344,179.86140663793083,174.3811558046037,174.96558860876283,39893600
3,2020-06-08,180.46502685546875,180.64706548139716,176.70933258630433,178.14646116671443,33211600
4,2020-06-09,181.8446502685547,182.70692146306783,179.41110465156908,180.12009326030233,29783900

In [3]:
# Check data shape and columns
print("Shape:", df.shape)
print("\nColumns:", df.columns)

# Summary statistics
df.describe()

Shape: (1256, 6)

Columns: Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

                                Date
count                           1255
mean   2022-11-30 12:32:42.071713280
min              2020-06-04 00:00:00
25%              2021-08-31 12:00:00
50%              2022-11-29 00:00:00
75%              2024-02-29 12:00:00
max              2025-06-02 00:00:00